M48
; DRILL file {KiCad 7.0.9} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-16T00:09:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
%
G90
G05
T1
X5.4862Y-4.0576
X5.7138Y-4.0576
T2
X2.7348Y-3.8726
X2.8044Y-3.9421
X2.9087Y-4.0465
X2.9783Y-4.1161
T3
X2.7Y-2.05
X3.25Y-4.15
X5.2Y-4.15
X5.7Y-3.3
T0
M30
