[build]
#target = "riscv32imac-esp-espidf"
target = "xtensa-esp32-espidf"

# None of those work:
#target_feather = "sparkfun"
#rustc-cfg = ['target_feather = "sparkfun"']
#rustflags = "--cfg target_feather=sparkfun"

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
rustflags = ["--cfg", "-C", "default-linker-libraries", "-C", "force-frame-pointers"]
# not on ESP32: "espidf_time64",

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.3"
#ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" } # so that this project won't contain another copy of the ESP IDF